### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by giswqs**
Addressing issue https://github.com/conda-forge/sktime-feedstock/issues/47 and https://github.com/conda-forge/autogluon.timeseries-feedstock/pull/9

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
@fkiraly @dhirschfeld @freddyaboulton @lmmentel @mloning The PR has passed the Python 3.10 checks. Can one of you review and merge it? We are wait for sktime to support Python 3.10 so that downstream packages can support Python 3.10.

**Comment by dhirschfeld** [comment]
This PR looks fine and upstream claim to support [`requires-python = ">=3.7,<3.12"`](https://github.com/sktime/sktime/blob/19618df351a27b77e3979efc191e53987dbd99ae/pyproject.toml#L41) so I think this is good to merge.

I'll give the upstream maintainers a chance to review though before applying EAFTP and merging myself...

**Review by dhirschfeld — APPROVED** [review]
:shipit:

**Pull request merged**
