### PR TITLE
[MNT] Removed hcrystalball dependency

### PR DESCRIPTION
**Pull request by aiwalter**

### CODE REVIEW

**Review by lmmentel — APPROVED** [review]

**Review by lmmentel — CHANGES_REQUESTED** [review]
There is another mention on hcrystalball in line 46

**Comment by aiwalter** [comment]
oh right, thx

**Review by lmmentel — APPROVED** [review]

**Comment by aiwalter** [comment]
@lmmentel can we actually also go for Python 3.10 with this?

**Comment by lmmentel** [comment]
Let's do a separate PR just the in case jobs start failing

**Pull request merged**
