### PR TITLE
manual release of `0.19.2` - attempting from fork

### PR DESCRIPTION
**Pull request by yarnabrina**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarnabrina** [comment]
@conda-forge-admin, please rerender

**Comment by yarnabrina** [comment]
@dhirschfeld @freddyaboulton @fkiraly given there was no automated PR for `0.19.2`, created this from my own fork modifying the `meta.yaml`. Please take a look and merge if this is all that is required to release the latest version in `conda-forge`.

Also, any idea why was this not auto-detected?

**Comment by fkiraly** [comment]
> Also, any idea why was this not auto-detected?

No, I'm also confused about it.
A very vague hypotesis is that there is some queue somewhere?

**Review by fkiraly — CHANGES_REQUESTED** [review]
URLs in the readme all point to "fork-feedstock", I think that should be this repository, no?

**Comment by yarnabrina** [comment]
I see what you mean, but those are auto-committed by re-render command. Do I need to edit those, or will these be auto-handled after merge when ran from `main`?

(I have no idea about what exactly happens in "re-rendering", so just asking for clarification.)

**Comment by dhirschfeld** [comment]
Not sure why the urls are getting mixed up. Perhaps a conda-smithy bug.

In any case, I tried to update using a bot command to see if it worked any better...

**Comment by fkiraly** [comment]
Ah, here it is:
https://github.com/conda-forge/sktime-feedstock/pull/90/files

Shall we go with #90 then?

**Comment by fkiraly** [comment]
I suppose I used the wrong command - should have used "update version", not re-render

**Comment by yarnabrina** [comment]
Closing in favour of #90.

**Pull request closed without merging**
